
export const metadata = {
    title: "Rs Community|About",
    description: "Generated by create next app",
  };

export default function Layout({children}){
    return(
        <div>         
           
            {children}
        </div>
        

    )
}